"""update model table

Revision ID: fb71ba41a8be
Revises: 32e0b4c9543c
Create Date: 2024-12-28 21:22:46.354922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb71ba41a8be'
down_revision: Union[str, None] = '32e0b4c9543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_model', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_chat_model_name', table_name='chat_model')
    op.create_index(op.f('ix_chat_model_value'), 'chat_model', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_model_value'), table_name='chat_model')
    op.create_index('ix_chat_model_name', 'chat_model', ['name'], unique=False)
    op.drop_column('chat_model', 'value')
    # ### end Alembic commands ###
