"""empty message

Revision ID: fe003046c896
Revises: 8a552590d875
Create Date: 2024-12-29 09:49:44.175130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe003046c896'
down_revision: Union[str, None] = '8a552590d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
